export interface Patient {
  id?: string;
  userId?: string;
  name: string;
  email?: string;
  phone?: string;
  birthDate?: string;
  address?: string;
  cpf?: string;
  anamnesis?: {
    // Dados Pessoais & Queixas
    mainComplaint: string;
    expectations: string;
    
    // Histórico Médico (Condições Fixas)
    conditions: {
      diabetes: boolean;
      hypertension: boolean;
      heartProblems: boolean;
      autoimmune: boolean;
      cancerHistory: boolean;
      keloid: boolean;
      herpes: boolean;
      epilepsy: boolean;
      hivHepatitis: boolean;
      pacemaker: boolean;
      pregnant: boolean;
      breastfeeding: boolean;
      anticoagulant: boolean;
      isotretinoin: boolean;
      contraceptive: boolean;
    };
    otherConditions: string;
    
    // Alergias e Medicações (Estruturadas)
    hasAllergies: boolean;
    allergiesDetails: string;
    hasContinuousMedication: boolean;
    medicationsDetails: string;
    
    familyHistory: string;
    
    // Hábitos
    habits: {
      smoking: boolean;
      alcohol: boolean;
      exercise: boolean;
      sunExposure: boolean;
      sunscreen: boolean;
      diet: string;
    };
    
    // Avaliação Clínica
    fitzpatrickType: 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI' | '';
    skinEvaluation: string;
    faceEvaluation: string;
  };
  photoHistory?: string[];
  files?: {
    name: string;
    url: string;
    type: string;
    date: string;
  }[];
  evolution?: {
    date: string;
    procedure: string;
    notes: string;
    bucoMaxiloNotes?: string;
    numericValue?: number;
    professionalId?: string;
  }[];
  consentTerms?: {
    templateId: string;
    templateTitle: string;
    signedAt: string;
    signatureUrl: string; // Base64 or URL
  }[];
  prescriptions?: {
    id: string;
    date: string;
    content: string;
    medicines: { name: string, dosage: string, instructions: string }[];
  }[];
  updatedAt?: string;
}

export interface Appointment {
  id?: string;
  userId?: string;
  patientId?: string; // opcional: agendamentos feitos pelo paciente direto na página pública não têm patientId
  patientName: string;
  guestPhone?: string; // telefone informado pelo paciente na página pública (quando não há cadastro ainda)
  date: string;
  time: string;
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled';
  notes?: string; // usado como descrição do procedimento
  value?: number;
  financeGenerated?: boolean; // evita duplicar lançamento financeiro ao concluir
  seriesId?: string; // agrupa ocorrências de um agendamento recorrente (pacote de sessões)
  checkedInAt?: string; // horário de chegada na recepção (fila de espera)
  checkinToken?: string; // token secreto usado no link de check-in do próprio paciente
  bookedOnline?: boolean; // true quando o próprio paciente agendou pela página pública
  createdAt?: string;
}

export interface InventoryItem {
  id?: string;
  userId?: string;
  code?: string;
  name: string;
  category: string;
  quantity: number;
  minThreshold: number;
  unit: string;
  supplier?: string;
  lastRestockDate?: string;
  expiryDate?: string;
}

// Histórico de consumo/reposição de estoque (feature adicionada depois, direto no AI Studio)
export interface InventoryMovement {
  id?: string;
  userId?: string;
  itemId: string;
  itemName: string;
  category?: string;
  quantity: number;
  type: 'consumption' | 'restock';
  date: string;
}

export interface ConsentTemplate {
  id?: string;
  title: string;
  content: string;
  category: 'cirurgico' | 'estetico' | 'geral';
}

export interface Transaction {
  id?: string;
  userId?: string;
  amount: number;
  type: 'income' | 'expense';
  date: any; // Firestore Timestamp
  category: string;
  description: string;
  patientId?: string;
  seriesId?: string; // agrupa lançamentos gerados por recorrência
  autoGenerated?: boolean; // criado automaticamente (ex: ao concluir consulta)
}

export interface ClinicSettings {
  professionalName: string;
  registrationNumber: string;
  clinicName: string;
  clinicAddress: string;
  contactEmail?: string;
  consentTemplates?: ConsentTemplate[];
  biometricEnabled?: boolean;
  pinHash?: string; // hash SHA-256 do PIN de 6 dígitos — nunca guardamos o PIN em texto puro
  webauthnCredentialId?: string; // id da credencial de biometria (Face ID/Touch ID/digital) — nenhum dado biométrico é guardado, só esse identificador
  cloudBackupEnabled?: boolean;
  whatsappNumber?: string;
}

// Documento público (legível por qualquer um, sem login) usado pela página de agendamento
// pra saber qual clínica é o "dono" deste app e mostrar o nome dela
export interface PublicBookingConfig {
  ownerId: string;
  clinicName: string;
  professionalName: string;
  whatsappNumber?: string;
}

// Marca um horário como ocupado — coleção pública (só data/hora, sem nenhum dado do paciente),
// usada pela página de agendamento pra saber quais horários mostrar como disponíveis.
export interface BusySlot {
  clinicId: string;
  date: string;
  time: string;
}
