export interface Patient {
  id?: string;
  userId?: string;
  name: string;
  email?: string;
  phone?: string;
  birthDate?: string;
  address?: string;
  cpf?: string;
  anamnesis?: {
    // Dados Pessoais & Queixas
    mainComplaint: string;
    expectations: string;
    
    // Histórico Médico (Condições Fixas)
    conditions: {
      diabetes: boolean;
      hypertension: boolean;
      heartProblems: boolean;
      autoimmune: boolean;
      cancerHistory: boolean;
      keloid: boolean;
      herpes: boolean;
      epilepsy: boolean;
      hivHepatitis: boolean;
      pacemaker: boolean;
      pregnant: boolean;
      breastfeeding: boolean;
      anticoagulant: boolean;
      isotretinoin: boolean;
      contraceptive: boolean;
    };
    otherConditions: string;
    
    // Alergias e Medicações (Estruturadas)
    hasAllergies: boolean;
    allergiesDetails: string;
    hasContinuousMedication: boolean;
    medicationsDetails: string;
    
    familyHistory: string;
    
    // Hábitos
    habits: {
      smoking: boolean;
      alcohol: boolean;
      exercise: boolean;
      sunExposure: boolean;
      sunscreen: boolean;
      diet: string;
    };
    
    // Avaliação Clínica
    fitzpatrickType: 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI' | '';
    skinEvaluation: string;
    faceEvaluation: string;
  };
  photoHistory?: string[];
  files?: {
    name: string;
    url: string;
    type: string;
    date: string;
  }[];
  evolution?: {
    date: string;
    procedure: string;
    notes: string;
    bucoMaxiloNotes?: string;
    numericValue?: number;
    professionalId?: string;
  }[];
  consentTerms?: {
    templateId: string;
    templateTitle: string;
    signedAt: string;
    signatureUrl: string; // Base64 or URL
  }[];
  prescriptions?: {
    id: string;
    date: string;
    content: string;
    medicines: { name: string, dosage: string, instructions: string }[];
  }[];
  updatedAt?: string;
}

export interface Appointment {
  id?: string;
  userId?: string;
  patientId: string;
  patientName: string;
  date: string;
  time: string;
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled';
  notes?: string; // usado como descrição do procedimento
  value?: number;
  financeGenerated?: boolean; // evita duplicar lançamento financeiro ao concluir
  seriesId?: string; // agrupa ocorrências de um agendamento recorrente
  createdAt?: string;
}

export interface InventoryItem {
  id?: string;
  userId?: string;
  code: string;
  name: string;
  category: string;
  quantity: number;
  minThreshold: number;
  unit: string;
  supplier: string;
  lastRestockDate?: string;
  expiryDate?: string;
}

export interface ConsentTemplate {
  id?: string;
  title: string;
  content: string;
  category: 'cirurgico' | 'estetico' | 'geral';
}

export interface Transaction {
  id?: string;
  userId?: string;
  amount: number;
  type: 'income' | 'expense';
  date: any; // Firestore Timestamp
  category: string;
  description: string;
  patientId?: string;
  seriesId?: string; // agrupa lançamentos gerados por recorrência
  autoGenerated?: boolean; // criado automaticamente (ex: ao concluir consulta)
}

export interface ClinicSettings {
  professionalName: string;
  registrationNumber: string;
  clinicName: string;
  clinicAddress: string;
  contactEmail?: string;
  consentTemplates?: ConsentTemplate[];
  biometricEnabled?: boolean;
  cloudBackupEnabled?: boolean;
}
